OpenSSL_include_x64 = "C:/Prog/Libs/openssl-1.0.2/include"
OpenSSL_libdir_x64 = "C:/Prog/Libs/openssl-1.0.2/lib/Win32/static/Release"
zlib_include = "C:/Prog/Libs/zlib-1.2.11"
zlib_libdir_x64 = "C:/Prog/Libs/zlib-1.2.11"
brotli_include = "C:/Prog/Libs/vcpkg/installed/x64-windows/include"
brotli_libdir_x64 = "C:/Prog/Libs/vcpkg/installed/x64-windows/lib"